config/routes.rb
App1::Application.routes.draw do
  
  get "users/new"

  root to: 'statis_pages#home'

  get 'help' => 'statis_pages#help'

  get 'about' => 'statis_pages#about'

  get 'contact' => 'statis_pages#contact'

  get 'signup' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum:10}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/statis_pages_controller.rb
class StatisPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Ruby on rails sample app"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/statis_pages_helper.rb
module StatisPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
			<%= link_to "sample app", root_path,id: "logo" %>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", root_path%></li>
					<li><%= link_to "Help", help_path%></li>
					<li><%= link_to "Log in", '#'%></li>
				</ul>
			</nav>
		</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
<%= render 'layouts/footer'%>
</div>
</body>
</html>

app/views/statis_pages/about.html.erb
<% provide(:title,"About")%>
<h2>This is about page.</h2>
<p>hjfdjhslksdjsd</p>

app/views/statis_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/statis_pages/help.html.erb
<%provide(:title,"Help")%>

	<h1>StatisPages#help</h1>
	<p>You can get help from <a href="https://www.google.co.in">here</a> and search anything.</p>

app/views/statis_pages/home.html.erb
<%provide(:title,"Home")%>
<div class="center jumbotron">
   <h1>Welcome to sample app</h1>
   <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
	<%= link_to "Sign up now!",signup_path,class: "btn btn-lg btn-primary"%>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>